### ISSUE TITLE
WCS_AH-64 and M2 Bradley Fighting Vehicle

### ISSUE THREAD

**Issue by Kekmit** [RHSMODS/statusquo#1106]
My unit just switched to Reforger and while working on our mod list, we noticed that the TOWs, and Hellfires doesn't work when you have RHS - Status Quo enabled. We did multiple tests including with the DEV version of RHS - Status Quo and noticed that it is only with RHS that prevents it from working. You can see the weaponry but you are unable to fire it. So far we have discovered it with the WCS_AH-64 and the M2 Bradley Fighting Vehicle mod same with the AH-1 from WCS_Helicopters.

**Comment by ajvorobiev** [comment]
i think the correct fix for this is putting RHS as the first loaded mod. This should be fixed in the future.

**Comment by Kekmit** [comment]
Attempted to load it first on the server and it still doesn't fire
